#!/bin/bash

. /opt/helpers

ICINGA2_FEATURE_INFLUXDB=${ICINGA2_FEATURE_INFLUXDB:-False}

# InfluxDB writer
if evaluate_boolean "${ICINGA2_FEATURE_INFLUXDB}"; then
	ICINGA2_FEATURE_INFLUXDB_HOST=${ICINGA2_FEATURE_INFLUXDB_HOST:-}
	ICINGA2_FEATURE_INFLUXDB_PORT=${ICINGA2_FEATURE_INFLUXDB_PORT:-8086}
	ICINGA2_FEATURE_INFLUXDB_DB=${ICINGA2_FEATURE_INFLUXDB_DB:-icinga2_db}
	ICINGA2_FEATURE_INFLUXDB_USER=${ICINGA2_FEATURE_INFLUXDB_USER:-icinga2}
	ICINGA2_FEATURE_INFLUXDB_PASS=${ICINGA2_FEATURE_INFLUXDB_PASS}
	ICINGA2_FEATURE_INFLUXDB_SSL=${ICINGA2_FEATURE_INFLUXDB_SSL:-True}

	echo "InfluxDB: Enabling Icinga2 InfluxDB writer"

	icinga2 feature enable influxdb --log-level critical

	cat >/etc/icinga2/features-available/influxdb.conf <<-END
	object InfluxdbWriter "influxdb" {
	  host = "${ICINGA2_FEATURE_INFLUXDB_HOST}"
	  port = ${ICINGA2_FEATURE_INFLUXDB_PORT}
	  database = "${ICINGA2_FEATURE_INFLUXDB_DB}"
	  username = "${ICINGA2_FEATURE_INFLUXDB_USER}"
	  password = "${ICINGA2_FEATURE_INFLUXDB_PASS}"
	  ssl_enable = ${ICINGA2_FEATURE_INFLUXDB_SSL}
	  enable_send_thresholds = true
	  enable_send_metadata = true
	  flush_threshold = 1024
	  flush_interval = 10s
	  host_template = {
	    measurement = "\$host.check_command$"
	    tags = {
	      hostname = "\$host.name$"
	    }
	  }
	  service_template = {
	    measurement = "\$service.check_command$"
	    tags = {
	      hostname = "\$host.name$"
	      service = "\$service.name$"
	    }
	  }
	}
	END
	echo -e "InfluxDB: Writer enabled and sending data to Influx agent at: ${ICINGA2_FEATURE_INFLUXDB_HOST:-}:${ICINGA2_FEATURE_INFLUXDB_PORT}\n"
else
	# Actively disable influxdb, to not hit any weird bugs
	icinga2 feature disable influxdb --log-level critical || true
fi
